#!/usr/bin/bash

USER_NAME=Bnyro
VOID_DIR=~/Projects/void-packages

prep_pkgs() {
	if [ ! -d "$VOID_DIR" ]; then
		git clone "git@github.com:$USER_NAME/void-packages" "$VOID_DIR"
		cd "$VOID_DIR"
		git remote add upstream "https://github.com/void-linux/void-packages.git"
		git fetch upstream
		git reset --hard upstream/master
		git push
	else
		cd "$VOID_DIR"
	fi
}

build() { # package/branch name, (optional) github user name of fork, e.g. Bnyro
	prep_pkgs
	if [ "$2" ]; then
		git remote add "$2" "https://github.com/$2/void-packages.git"
		git fetch "$2"
		git checkout "$2"/"$1"
		git merge upstream/master --no-edit
	else
		git checkout "$1"
	fi
	./xbps-src binary-bootstrap
	./xbps-src clean
	./xbps-src pkg "$1"
	xi "$1"
}

bump() { # package name, new version to update to
	prep_pkgs
	git checkout -b "$1"
	git reset --hard upstream/master
	TEMPLATE="srcpkgs/$1/template"
	# update the version
	sed -i "0,/version=[0-9\.]*/s//version=$2/" "$TEMPLATE"
	# reset the revision
	sed -i "0,/revision=[0-9]*/s//revision=1/" "$TEMPLATE"
	xgensum -i "$1"
	./xbps-src pkg "$1" || exit 1
	xi -y "$1"
	xbump "$1"
	git push --set-upstream origin "$1"
	git checkout master
}

update() {
	sudo xbps-install -Syu
	sudo xbps-remove -O
	sudo rm -rf /var/cache/* /var/tmp/*
	sudo vkpurge rm all
}

check() {
	prep_pkgs
	packages=$(xpkg "$1" | sed '/^.*32bit$/d')
	updates=$(echo "$packages" | while read line; do
		./xbps-src update-check $line 2>/dev/null &
	done)
	echo "$updates" | tac | sort -u -t ">" -k1,1
}

case ${1} in
update) update ;;
check) check "$2" ;;
build) build "$2" "$3" ;;
bump) bump "$2" "$3" ;;
esac
