#!/usr/bin/bash

PROJECTS_DIR=~/Projects
USER_NAME=Bnyro

prep_pkgs() {
	cd "$PROJECTS_DIR"
	[ ! -d "void-packages" ] && git clone "git@github.com:$USER_NAME/void-packages"
	cd "void-packages"
}

pkg() { # package/branch name, (optional) github user name of fork, e.g. Bnyro
	prep_pkgs
	if [ -z "$2" ]; then
		git remote add "$2" "https://github.com/$2/void-packages.git"
		git fetch "$2"
		git checkout "$2"/"$1"
	else
		git checkout "$1"
	fi
	./xbps-src binary-bootstrap
	./xbps-src clean
	./xbps-src pkg "$1"
	xi "$1"
}

update() {
	sudo xbps-install -Syu
	sudo xbps-remove -O
	sudo rm -rf /var/cache/* /var/tmp/*
	sudo vkpurge rm all
}

updatecheck() {
	prep_pkgs
	xpkg -m | while read line; do ./xbps-src update-check $line & done
}

case ${1} in
update) update ;;
updatecheck) updatecheck ;;
pkg) pkg "$2" "$3" ;;
esac
